In [1]:
import os
import pandas as pd

- Option 1: Converting table rows to text: This approach transforms each table row into a natural language description. Column headers become context labels, and values are integrated into readable text
- Option 2: Embedding tables in prompts:
As an alternative to converting rows into individual text snippets, you can embed the entire table directly into the LLM prompt. This works best for small tables whose full context fits into the model’s context window.

In [4]:
file_path = "../datasets/csv_files/census-income.xlsx"
df_excel = pd.read_excel(io=file_path)

In [5]:
df_excel.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
def create_text_description_of_row(row):
    row["text_description"] = (
        f"""The candidate {row['age']} years old is working in the
            {row['workclass']} sector. The candidate was born in
            {row['native-country']}, is {row['marital-status']}
            and has a {row['relationship']} relationship.
            The candidate has a {row['education']} degree and is
            working as a {row['occupation']}. The income of the
            candidate is {row['income']}."""
    )

    return row

df_extended = df_excel.apply(create_text_description_of_row, axis=1)

In [14]:
df_extended["text_description"][0].replace('\n', ' ')

'The candidate 39 years old is working in the             State-gov sector. The candidate was born in             United-States, is Never-married             and has a Not-in-family relationship.             The candidate has a Bachelors degree and is             working as a Adm-clerical. The income of the             candidate is <=50K.'

In [15]:
df_excel.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K